apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoapp-deployment
  labels:
    app: mongoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
        - name: mongoapp
          image: sanuga/dockerhub:7.0
          ports:
            - containerPort: 8888
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoapp-service
spec:
  type: NodePort
  selector:
    app: mongoapp
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30100
